Document: util-linux
Title: Debian util-linux Manual
Author: <insert document author here>
Abstract: This manual describes what util-linux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/util-linux/util-linux.sgml.gz

Format: postscript
Files: /usr/share/doc/util-linux/util-linux.ps.gz

Format: text
Files: /usr/share/doc/util-linux/util-linux.text.gz

Format: HTML
Index: /usr/share/doc/util-linux/html/index.html
Files: /usr/share/doc/util-linux/html/*.html
